name: Next.js CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: 游빛 Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 Checkout Code
        uses: actions/checkout@v3

      - name: 游릭 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: 游닍 Install Dependencies
        run: npm install

      - name: 游댌 Run ESLint
        run: npm run lint

  build:
    name: 游끵 Build Project
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: 游닌 Checkout Code
        uses: actions/checkout@v3

      - name: 游릭 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: 游닍 Install Dependencies
        run: npm install

      - name: 游 Build Project
        run: npm run build